name: Feature Request
description: Proposer une nouvelle fonctionnalité
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problème à résoudre
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Solution proposée
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considérées
